[package]
name = "convertible_couch"
version = "0.9.0"
edition = "2021"
authors = ["Thomas PEREZ"]
description = "Automate Windows display configuration to play from your couch"
readme = "../README.md"
repository = "https://github.com/drsanguin/convertible_couch"
license-file = "../LICENSE"

[package.metadata.winresource]
LegalCopyright = "Copyright © 2024 convertible_couch"
OriginalFilename = "convertible_couch.exe"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
log = "0.4.21"
convertible_couch_lib = { path = "../lib"}

[build-dependencies]
winresource = "0.1.17"
