[package]
name = "convertible_couch"
version = "1.0.0"
edition = "2021"
authors = ["Thomas PEREZ"]
description = "Automate Windows display configuration to play from your couch"
readme = "../README.md"
repository = "https://github.com/drsanguin/convertible_couch"
license-file = "../LICENSE"

[package.metadata.winresource]
LegalCopyright = "Copyright © 2024 convertible_couch"
OriginalFilename = "convertible_couch.exe"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
log = "0.4.28"
convertible_couch_lib = { path = "../lib"}

[build-dependencies]
winresource = "0.1.23"

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
test-case = "3.3.1"

[target.'cfg(windows)'.dev-dependencies]
windows = { version = "0.62.1", features = ["Win32_Graphics_Gdi"] }

[[bench]]
name = "benchmark"
harness = false