name: Linting 📝
description: Catch all common Rust code mistakes
inputs:
  github-token:
    description: "GitHub API token"
    required: true
runs:
  using: composite
  steps:
    - name: Install clippy 🧰
      run: rustup component add clippy
      shell: pwsh

    - name: Run clippy 📝
      run: cargo clippy --all-targets --all-features -- -D warnings
      shell: pwsh