version: 2
updates:
  - package-ecosystem: github-actions
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    commit-message:
      prefix: build
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
          
  - package-ecosystem: cargo
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    commit-message:
      prefix: build
      include: scope
    groups:
      cargo:
        patterns:
          - "*"
          
  - package-ecosystem: rust-toolchain
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    commit-message:
      prefix: build
      include: scope
    groups:
      rust-toolchain:
        patterns:
          - "*"