name: Run Mutation Testing 🧟
description: Evaluate the quality of existing tests
runs:
  using: composite
  steps:
    - name: Install cargo-mutants 🧰
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-mutants

    - name: Generate git.diff 🧰
      if: github.event.pull_request.base.ref == 'develop'
      shell: pwsh
      run: git diff origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} > git.diff

    - name: Run cargo-mutants on the entire codebase 🧟‍♂️
      id: run-cargo-mutants-on-the-entire-codebase
      if: github.event.pull_request.base.ref != 'develop'
      shell: pwsh
      run: cargo mutants --all-features --no-shuffle --in-place --test-workspace=true

    - name: Run cargo-mutants only on recently changed code 🧟‍♂️
      id: run-cargo-mutants-on-recently-changed-code
      if: github.event.pull_request.base.ref == 'develop'
      shell: pwsh
      run: cargo mutants --all-features --no-shuffle --in-place --test-workspace=true --in-diff git.diff

    - name: Archive results ⬆️
      uses: actions/upload-artifact@v4
      if: steps.run-cargo-mutants-on-the-entire-codebase.outcome == 'failure' || steps.run-cargo-mutants-on-recently-changed-code == 'failure'
      with:
        name: mutation-testing-report
        path: mutants.out