exclude_globs = [
    "bin/src/main.rs",
    "lib/src/testing/**/*.rs",
    "lib/src/display_settings/windows/win_32/windows_api_based_win_32.rs",
    "lib/src/sound_settings/windows/audio_endpoint_library/dll_based_audio_endpoint_library.rs"
    ]
exclude_re = [
    "configure_logger", # this function is just side effect
    ]