name: Upload Code Coverage 📊
description: Generate and upload code coverage
inputs:
  github-token:
    description: "GitHub API token"
    required: true
  test-type:
    description: "Test type"
    required: true
    type: choice
    options:
      - unit
      - integration

runs:
  using: composite
  steps:
    - name: Install llvm-tools 🧰
      shell: pwsh
      run: rustup component add llvm-tools

    - name: Run Unit Tests 🧪
      if: ${{ inputs.test-type == 'unit' }}
      env:
        RUSTFLAGS: -Cinstrument-coverage
        LLVM_PROFILE_FILE: convertible_couch-%p-%m.profraw
      shell: pwsh
      run: cargo test --lib --bins

    - name: Run Integration Tests 🧪
      if: ${{ inputs.test-type == 'integration' }}
      env:
        RUSTFLAGS: -Cinstrument-coverage
        LLVM_PROFILE_FILE: convertible_couch-%p-%m.profraw
      shell: pwsh
      run: cargo test --test *

    - name: Install grcov 🧰
      uses: taiki-e/install-action@v2
      with:
        tool: grcov

    - name: Generate lcov Coverage 📊
      shell: pwsh
      run: |
        grcov . `
          --binary-path ./target/debug/ `
          --output-types lcov `
          --source-dir . `
          --branch `
          --output-path lcov.info `
          --ignore-not-existing `
          --ignore C:/*/.cargo/* `
          --ignore testing/* `
          --ignore */tests/* `
          --ignore bin/src/main.rs `
          --ignore */build.rs `
          --ignore lib/src/displays_settings/windows/win_32/windows_api_based_win_32.rs `
          --ignore lib/src/speakers_settings/windows/windows_com/windows_api_based_windows_com/* `
          --excl-line "^\s*#\[cfg\(test\)\]" `
          --excl-start "^(\s*mod should \{)|(pub fn configure_logger\()|(impl From<ConfigErrors> for ApplicationError \{)|(impl From<SetLoggerError> for ApplicationError \{)" `
          --excl-stop "^\}"

    - name: Upload Coverage to Coveralls ⬆️
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ inputs.github-token }}
        file: lcov.info
        flag-name: ${{ inputs.test-type == 'unit' && 'Unit' || 'Integration' }}
        parallel: true