name: Prepare Release

on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install cargo-edit 🧰
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit

      - name: Semantic Release 🚀
        run: npx semantic-release --dry-run | Tee-Object semantic_release_output.log

      - name: Bump Version 🏷️
        run: |
          Select-String -Path .\semantic_release.log -Pattern "The next release version is" | `
            ForEach-Object { $_.Line } | `
            ForEach-Object { $_ -split " " } | `
            Select-Object -Last 1 | `
            ForEach-Object { cargo set-version --workspace $_ }

      - name: Push New Version ⬆️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = cargo metadata --no-deps --format-version 1 `
            | ConvertFrom-Json `
            | %{ $_.packages[0].version }

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml **/Cargo.toml Cargo.lock
          git commit -m "chore(metadata): bump version to $version"
          git push origin HEAD