name: Pull Request main/develop

on:
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-pull-request:
    name: Check Pull Request 📝
    runs-on: windows-latest

    steps:
    - name: Checkout Repository ⬇️
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Check Coding Style 📝
      run: cargo fmt --check --all

    - name: Compile Project 🏗️
      run: cargo build --all-targets --verbose
      env:
        RUSTFLAGS: -D warnings

    - name: Run Linting 📝
      uses: ./.github/actions/run-linting

    - name: Run Tests 🧪
      run: cargo test --verbose -- --nocapture

    - name: Run Mutation Tests 🧟
      uses: ./.github/actions/run-mutation-testing

    - name: Run Smoke Tests 🚬
      run: cargo run -r info -l trace

    - name: Run Benchmarks ⏱️
      run: cargo test --benches

    - name: Upload Code Coverage 📊
      uses: ./.github/actions/upload-code-coverage
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}