name: Push release/hotfix

on:
  push:
    branches:
      - ci/refactor-semantic-release-steps

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump Version 🏷️
    runs-on: windows-latest

    steps:
      - name: Checkout Repository ⬇️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # - name: Run Semantic Release 🚀
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release --dry-run | Tee-Object semantic_release.log

      - name: Get next release version 🏷️
        id: get-next-release-version
        run: |
          $nextReleaseVersion = Select-String -Path .\semantic_release.log -Pattern "The next release version is" |
            ForEach-Object { $_.Line } |
            ForEach-Object { $_ -split " " } |
            Select-Object -Last 1

          if ([string]::IsNullOrWhiteSpace($nextReleaseVersion)) {
            Write-Error "❌ Release version not found in semantic_release.log"
            exit 1
          }

          Write-Host "✅ Found version: $nextReleaseVersion"

          # Set step output
          "version=$nextReleaseVersion" >> $env:GITHUB_OUTPUT

      - name: Bump Version 🏷️
        run: |
          $regex = '^version = "\d+\.\d+\.\d+"'

          Get-ChildItem -Recurse -Filter "Cargo.toml" | ForEach-Object {
              Write-Host "Updating $($_.FullName)"

              $content = Get-Content $_.FullName -Raw
              $updated = [regex]::Replace(
                  $content,
                  $regex,
                  "version = "${{steps.get-next-release-version.outputs.version }}"
              )

              Set-Content $_.FullName $updated -NoNewline
          }

          cargo update --workspace

      - name: Push Metadata Changes ⬆️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml **/Cargo.toml Cargo.lock
          git commit -m "chore(metadata): bump version to ${{steps.get-next-release-version.outputs.version }}"
          git push origin HEAD