# name: Push main/develop

# on:
#   push:
#     branches: [ "main", "develop" ]
#   workflow_dispatch:

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   upload-coverage:
#     name: Upload Code Coverage 📊
#     runs-on: windows-latest

#     steps:
#     - name: Checkout Repository ⬇️
#       uses: actions/checkout@v6

#     - name: Code Coverage 📊
#       uses: ./.github/actions/upload-code-coverage
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}