name: Push main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    name: Release New Version 🚀
    runs-on: windows-latest

    steps:
      - name: Checkout Repository ⬇️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Dev Environment 🧰
        uses: ./.github/actions/setup-dev-environment

      - name: Compile Project 🏗️
        run: cargo build --release --bins

      - name: Package Artifacts 📦
        run: Compress-Archive -Path .\target\release\*.exe, .\target\release\*.dll -DestinationPath convertible_couch.zip

      - name: Run Semantic Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release