name: Push main/develop

on:
  push:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-coverage:
    name: Upload Code Coverage 📊
    runs-on: windows-latest

    steps:
    - name: Checkout Repository ⬇️
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Setup Dev Environment 🧰
      uses: ./.github/actions/setup-dev-environment

    - name: Code Coverage 📊
      uses: ./.github/actions/upload-code-coverage
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}