name: Push main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    name: Release New Version 🚀
    runs-on: windows-latest

    steps:
      - name: Checkout Repository ⬇️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Compile Project 🏗️
        run: cargo build --release --bins --target x86_64-pc-windows-msvc

      - name: Package Artifacts 📦
        run: Compress-Archive -Path .\target\x86_64-pc-windows-msvc\release\convertible_couch.exe -DestinationPath convertible_couch-x86_64-pc-windows-msvc.zip

      - name: Run Semantic Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release